import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import getCurrentUser from "./actions/getCurrentUser";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const currentUser = getCurrentUser();
	return (
		<html lang="en">
			<body className={`dark ${inter.className} bg-zinc-900 min-h-screen`}>
				<Navbar currentUser={currentUser} />
				{children}
			</body>
		</html>
	);
}
